#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f /etc/nixos/hardware-configuration.nix ]; then
  echo "Error: /etc/nixos/hardware-configuration.nix not found."
  echo "  Run 'nixos-generate-config' first."
  exit 1
fi

echo "[1/6] Reading hardware config..."

HW="/etc/nixos/hardware-configuration.nix"
initrd_modules=$(grep "boot.initrd.availableKernelModules" "$HW" | sed 's/.*= \[//;s/\];.*//;s/^[[:space:]]*//')
kvm_modules=$(grep "boot.kernelModules" "$HW" | sed 's/.*= \[//;s/\];.*//;s/^[[:space:]]*//')

extract_device() {
  local mount="$1"
  awk "/\"${mount}\"[[:space:]]*=/,/};/" "$HW" \
    | grep -m1 "device" \
    | sed 's/.*device = "\(.*\)";.*/\1/'
}

root_device=$(extract_device "/" || true)
boot_device=$(extract_device "/boot" || true)
root_device="${root_device:-REPLACE_ME}"
boot_device="${boot_device:-REPLACE_ME}"

echo "[2/6] Gathering identity..."

read -r -p "  Hostname [legion]: " HOSTNAME
HOSTNAME="${HOSTNAME:-legion}"
read -r -p "  Username [${HOSTNAME}]: " USERNAME
USERNAME="${USERNAME:-$HOSTNAME}"
echo -n "  Password: "
HASHED=$(mkpasswd)
HASHED="${HASHED//$/\$}"
echo

echo "[3/6] Writing host facts..."

mkdir -p "$REPO_DIR/nixos/constants/hosts"
cat > "$REPO_DIR/nixos/constants/hosts/${HOSTNAME}.nix" << NIXEOF
# constants/hosts/${HOSTNAME}.nix — generated by bootstrap.sh; edit to taste.
{
  hostname = "${HOSTNAME}";
  username = "${USERNAME}";
  homeDirectory = "/home/${USERNAME}";
  timezone = "Asia/Amman";
  locale = "en_US.UTF-8";
  stateVersion = "26.05";

  users = { };

  # Assemblies composed into this host (assemblies/<name>.nix).
  assemblies = [
    "desktop"
    "development"
    "gaming"
    "media"
    "virtualization"
  ];

  compositors = [ "niri" ];

  boot = {
    initrdAvailableKernelModules = [ ${initrd_modules} ];
    kernelModules = [ ${kvm_modules} ];
    zswap = true;
  };

  swap = {
    device = "/swapfile";
    size = 8192;
  };

  disks = {
    root = "${root_device}";
    boot = "${boot_device}";
  };

  # NVIDIA bus IDs (only needed for hybrid GPUs).
  gpu = { };
  #   nvidiaBusId = "PCI:1:0:0";
  #   intelBusId = "PCI:0:0:0";

  efi = {
    secureBoot = false;
    canTouchEfiVariables = true;
  };
}
NIXEOF

echo "[4/6] Writing host module..."

cat > "$REPO_DIR/nixos/hosts/${HOSTNAME}.nix" << NIXEOF
# hosts/${HOSTNAME}.nix — ${HOSTNAME} facts + machine-level modules.
# Composition (assemblies, compositors) lives in constants/hosts/${HOSTNAME}.nix.
{ lib, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  my.host = import ../constants/hosts/${HOSTNAME}.nix;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  users.users.${USERNAME}.hashedPassword = "${HASHED}";
}
NIXEOF

echo "[5/6] Staging changes for NixOS build..."
cd "$REPO_DIR"
git add -A

echo "[6/6] Building NixOS..."
cd "$REPO_DIR/nixos"
sudo nixos-rebuild switch --flake ".#${HOSTNAME}"

echo "Done. After this, just run: nh os switch"
